//layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CopilotKit } from "@copilotkit/react-core";
import { Suspense } from "react";
import { AgentProvider } from "@/contexts/agentContext";
import { ModelProvider } from "@/contexts/modelContext";
import { LanguageProvider } from "@/contexts/languageContext";
import { ResearchProvider } from "@/lib/research-provider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { useLgc } = useModelSelectorContext();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <Suspense> {children}</Suspense>
          
      </body>
    </html>
  );
}


